"""empty message

Revision ID: 1b95a49b3f1c
Revises: d4a62b9ca93a
Create Date: 2023-07-30 19:36:15.064191

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b95a49b3f1c'
down_revision = 'd4a62b9ca93a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('artist', schema=None) as batch_op:
        batch_op.add_column(sa.Column('starttime', sa.Time(), nullable=False))
        batch_op.add_column(sa.Column('endtime', sa.Time(), nullable=False))

    with op.batch_alter_table('group', schema=None) as batch_op:
        batch_op.add_column(sa.Column('owner_id', sa.Integer(), nullable=False))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('username',
               existing_type=sa.VARCHAR(length=80),
               nullable=False)
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=80),
               nullable=True)
        batch_op.create_unique_constraint(None, ['username'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=80),
               nullable=False)
        batch_op.alter_column('username',
               existing_type=sa.VARCHAR(length=80),
               nullable=True)

    with op.batch_alter_table('group', schema=None) as batch_op:
        batch_op.drop_column('owner_id')

    with op.batch_alter_table('artist', schema=None) as batch_op:
        batch_op.drop_column('endtime')
        batch_op.drop_column('starttime')

    # ### end Alembic commands ###
